### ISSUE TITLE
Nested VM environment

### ISSUE THREAD

**Issue by sokunna** [Azure/AKS-Edge#178] opened 2024-04-12 13:15 UTC
I’m looking at the documentation here https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-nested-environment and it says that only VMware ESXi is supported for production. Is Microsoft planning to support other nested VM environment (such as Hyper-V or Nutanix) in the future roadmap? If so, when would it be available? If not, what were the rational not to support?

**Comment by scooley** [comment] 2024-05-01 23:50
Yes, we want great AKS solutions in VM environments.  What's your use case?

**Comment by scholz** [comment] 2024-09-30 08:59
Hi @scooley  / @SummerSmith , as the original poster did not answer yet:

Our use-case is relatively straight forward. We aim to deliver a product on AKSEE where more than 3/4 of customers have already expressed that they would like to virtualize the solution instead of receiving a HW device. We have confirmed, as described in AKSEE  documentation, that AKSEE works on VMware/vSphere which also still seems to be the most prominent solution with the customers.
We have also read that nested virtualization is not so common (e.g. proxmox envs seem to be difficult). However, customers may not have VMWare to begin with or switch to a different solution due to the Broadcom aquisition and on-going confusion. Hence, if they exist - more details or plans on (even probably) supporting / supported virtual envs would be super helpful :)

**Comment by parameshbabu** [comment] 2024-10-01 20:33
Hi @scholz , We do support nested virtualizations on Hyper-V ( as you can already validate many of the scenarios on Azure VM, for example). Azure Arc Jumpstart scenarios are built on Azure VMs that do make use of nested virtualization on Hyper-V. 
So, Hyper-V and the VMWare ESXi are supported. Now if there is a reason for running this on Nutanix or other virtualization tech, let us know.

**Comment by scholz** [comment] 2024-10-02 10:03
Hi @parameshbabu , thanks for your reply and the explaination. Right now, I do not have concrete names of other virtualization products that are employed, but I will reach out to CSMs / POs to ask if they can name such concrete examples that customers are using.
The idea with my request above was also - that in case that you had a more comprehensive list of virtualization platforms that are not officially supported but might be working - to take that list and show to internal mgmt/deciders/critics that even if customers do not have vmware or hyper-v also others are generally possible.

**Comment by parameshbabu** [comment] 2024-10-02 16:53
@scholz, thanks for sharing your perspective here.  We have not explored another virtualization tech as we haven't seen any demand so far.

**Comment by parameshbabu** [comment] 2024-12-02 22:37
Closing as there is no outstanding action here.

**Closed by parameshbabu** 2024-12-02 22:37 UTC
Labels: enhancement
